package examples

import java.io.{File, PrintWriter}
import java.sql.DriverManager
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

import com.uber.engsec.dp.analysis.histogram.HistogramAnalysis
import com.uber.engsec.dp.rewriting.differential_privacy.{ElasticSensitivityConfig, ElasticSensitivityRewriter, SampleAndAggregateConfig, SampleAndAggregateRewriter}
import com.uber.engsec.dp.schema.Schema
import com.uber.engsec.dp.sql.QueryParser
import com.uber.engsec.dp.util.ElasticSensitivity


import scala.io.Source
import scala.util.parsing.json.JSON

/** A simple example demonstrating query rewriting for differential privacy.
  */
object QueryRewritingExample extends App {
  // Use the table schemas and metadata defined by the test classes
  System.setProperty("schema.config.path", "schema.yaml.template")


  // variable to store JSON string extracted from the file
  var jsonStr = ""

  // variable to store last modified file
  var lastFileCreated = ""

  // give path where JSON files are created by simpleServer.py

  val path: String = "/root/files/jsonreq/"

  // privacy budget
  val EPSILON = 0.1

  // delta parameter: use 1/n^2, with n = 100000
  val DELTA = 1 / (math.pow(100000, 2))

  // Helper function to print queries with indentation.
  def printQuery(query: String) = println(s"\n  " + query.replaceAll("\\n", s"\n  ") + "\n")


  val t = new java.util.Timer()
  val task = new java.util.TimerTask {
    def run() = {


      // get the name of the latest file created by simpleServer.py
      val dir: File = new File(path)
      val files: Array[File] = dir.listFiles()
      if (files == null || files.length == 0) {
        throw new NoSuchElementException ("No files exist!")
      }
      var tempLastFileCreated: File = files(0)
      var i = 0
      for (i <- 1 until files.length) {
        if (tempLastFileCreated.lastModified() < files(i).lastModified()) {
          tempLastFileCreated = files(i)
        }
      }

      // check if any new file has been generated by simpleServer.py
      if (tempLastFileCreated.toString != lastFileCreated) {

        // update the name of the latest file created by simpleServer.py
        lastFileCreated = tempLastFileCreated.toString
        // append filename to the filepath
        val filename: String = lastFileCreated


        // read file to process JSON String
        for (line <- Source.fromFile(filename).getLines) {
          jsonStr = line;
        }


        // extract the query from the JSON
        val resultOption = JSON.parseFull(jsonStr) match {
          case Some(map: Map[String, String]) => map.get("query")
          case _ => None
        }
        val query = resultOption.get

        // extract database name from the JSON file
        val resultDbName = JSON.parseFull(jsonStr) match {
          case Some(map: Map[String, String]) => map.get("dbname")
          case _ => None
        }
        val dbName = resultDbName.get

        //Enter the database name from schema
        val database = Schema.getDatabase(dbName)


        // create connection to database
        classOf[org.postgresql.Driver]

        // enter appropriate credentials to connect to server
        val con_str = "jdbc:postgresql://db001.gda-score.org:5432/" + dbName + "?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&user=rohan@rhrk.uni-kl.de&password=WqResadfekaing7mk"

        val conn = DriverManager.getConnection(con_str)

        def elasticSensitivityExample() = {
          println("*** Elastic sensitivity example ***")

          // Example query given in Uber repository
          /*val query = """
                        |SELECT COUNT(*) FROM orders
                        |JOIN customers ON orders.customer_id = customers.customer_id
                        |WHERE orders.product_id = 1 AND customers.address LIKE '%United States%'"""
            .stripMargin.stripPrefix("\n")*/

          // Print the example query and privacy budget
          val root = QueryParser.parseToRelTree(query, database)
          println("Original query:")
          printQuery(query)
          println(s"> Epsilon: $EPSILON")

          // Compute mechanism parameter values from the query. Note the rewriter does this automatically; here we calculate
          // the values manually so we can print them.
          val elasticSensitivity = ElasticSensitivity.smoothElasticSensitivity(root, database, 0, EPSILON, DELTA)
          println(s"> Elastic sensitivity of this query: $elasticSensitivity")
          println(s"> Required scale of Laplace noise: 2 * $elasticSensitivity / $EPSILON = ${2 * elasticSensitivity / EPSILON}")

          // Rewrite the original query to enforce differential privacy using Elastic Sensitivity.
          println("\nRewritten query:")
          val config = new ElasticSensitivityConfig(EPSILON, DELTA, database)
          val rewrittenQuery = new ElasticSensitivityRewriter(config).run(query)
          printQuery(rewrittenQuery.toSql())

          // write noisy result to .txt file with timestamp

          new PrintWriter("/root/files/noisyres/result" + LocalDateTime.now.format(DateTimeFormatter.ofPattern("YYYY-MM-dd_HH-mm-ss")) + ".txt") {
            write(rewrittenQuery.toSql());
            close
          }
          println("File Created!")
        }

        def sampleAndAggregateExample() = {
          println("*** Sample and aggregate example ***")
          val LAMBDA = 2.0

          // Print the example query and privacy budget
          val root = QueryParser.parseToRelTree(query, database)
          println("Original query:")
          printQuery(query)
          println(s"> Epsilon: $EPSILON")

          // Compute mechanism parameter values from the query. Note the rewriter does this automatically; here we calculate
          // the values manually so we can print them.
          val analysisResults = new HistogramAnalysis().run(root, database).colFacts.head
          println(s"> Aggregation function applied: ${analysisResults.outermostAggregation}")
          val tableName = analysisResults.references.head.table
          val approxRowCount = Schema.getTableProperties(database, tableName)("approxRowCount").toLong

          println(s"> Table being queried: $tableName")
          println(s"> Approximate cardinality of table '$tableName': $approxRowCount")
          println(s"> Number of partitions (default heuristic): $approxRowCount ^ 0.4 = ${math.floor(math.pow(approxRowCount, 0.4)).toInt}")
          println(s"> Lambda: $LAMBDA")

          // Rewrite the original query to enforce differential privacy using Sample and Aggregate.
          println("\nRewritten query:")
          val config = new SampleAndAggregateConfig(EPSILON, LAMBDA, database)
          val rewrittenQuery = new SampleAndAggregateRewriter(config).run(query)
          printQuery(rewrittenQuery.toSql())
        }

        elasticSensitivityExample()
        sampleAndAggregateExample()


      }

    }
  }

  // schedule the task to check for new files and execute if new files are found
  t.schedule(task, 100L, 100L)
  task.run()
}